### ISSUE TITLE
Clases created using @Provides or providers aren't part of lifecycle

### ISSUE THREAD

**Issue by danchia** [Netflix/governator#104]
Guice doesn't consider these classes as "injected", so LifecycleManager isn't made aware of them.

Not necessarily a bug, but might not be behavior people expect.

For singleton objects that need warmup / preDestroy, they can be manually added the LifecycleManager as a workaround it seems.

**Comment by asafm** [comment]
I just stumbled upon that. 

1. I don't understand why when @Provides method is used it's not going through the injector - The framework that runs the @Provides method is Guice when you run Guice.createInjector() right? So why Govrenator Lifecycle Injector can't interact with it? Can't it intercept any instance created whether it was created by @Inject or by @Provides and manage its lifecycle?

2. I think this behavior should be documented insde the Lifecycle wiki page - I can fix it if you agree.

**Comment by brharrington** [comment]
I think this was fixed, see #276 .
