### ISSUE TITLE
1.4.0 on Maven Central

### ISSUE THREAD

**Issue by jsmodic** [Netflix/governator#195]
Can you upload governator 1.4.0 to Maven Central? The latest there is still 1.3.3.

Thanks!

**Comment by jdente** [comment]
I second this request. We need to keep **org.codehaus.map.jackson** libraries out of our code base and it appears you made the switch to **com.fasterxml.jackson** in 1.4.0.

**Comment by jdente** [comment]
Would like to bump this issue up to 1.7.1 which I see you guys just released. If the artifacts are not available on Maven Central, can you please post them elsewhere? I noticed your release archives are simply source archives and do not contain your blessed jars. Currently we are having to build these artifacts ourselves on our own local environment, which is not the right approach.

**Comment by rspieldenner** [comment]
They are posted to Bintray currently. Working through reclaiming other
jcenter repos publishing this from 3rd parties and setting up the maven
central sync.

**Comment by jdente** [comment]
Bintray is fine for me for now. Thank you!
