### ISSUE TITLE
Allow for overriding modules.

### ISSUE THREAD

**Issue by noel-yap** [Netflix/governator#376]
For some tests (eg integration), it would be useful to be able to override specific modules so that fakes or other doubles may be bound (as described in https://stackoverflow.com/questions/483087/overriding-binding-in-guice).

**Comment by elandau** [comment]
Is this in the context of the GovernatorJunit4ClassRunner or using InjectorBuilder directly?  Are you recommending @ModulesForTesting have an overrideModules property.  Alternatively you could have a single module passed to @ModulesForTesting and using Modules.override in that module.

**Comment by twicksell** [comment]
+1 for single module which uses Modules.override. I consciously did not make a second attribute for @ModulesForTesting because I did not want to unnecessarily complicate that testing pattern.

**Comment by noel-yap** [comment]
For future reference, the above would look something like:

```
public class UnitTestingModule extends AbstractModule {
    @Override
    protected void configure() {
        install(Modules.override(new ProdModule()).with(new FakeModule()));
    }    
}
```
